// Generated by gencpp from file robot_vision/BoundingBox.msg
// DO NOT EDIT!


#ifndef ROBOT_VISION_MESSAGE_BOUNDINGBOX_H
#define ROBOT_VISION_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_vision
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , confidence(0.0)
    , Class()  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , confidence(0.0)
    , Class(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _xmin_type;
  _xmin_type xmin;

   typedef int64_t _ymin_type;
  _ymin_type ymin;

   typedef int64_t _xmax_type;
  _xmax_type xmax;

   typedef int64_t _ymax_type;
  _ymax_type ymax;

   typedef double _confidence_type;
  _confidence_type confidence;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Class_type;
  _Class_type Class;





  typedef boost::shared_ptr< ::robot_vision::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_vision::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::robot_vision::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::robot_vision::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::robot_vision::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_vision::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_vision::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_vision::BoundingBox_<ContainerAllocator1> & lhs, const ::robot_vision::BoundingBox_<ContainerAllocator2> & rhs)
{
  return lhs.xmin == rhs.xmin &&
    lhs.ymin == rhs.ymin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymax == rhs.ymax &&
    lhs.confidence == rhs.confidence &&
    lhs.Class == rhs.Class;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_vision::BoundingBox_<ContainerAllocator1> & lhs, const ::robot_vision::BoundingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_vision::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_vision::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_vision::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_vision::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_vision::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_vision::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_vision::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1784bb36e3cc3f55b84f76dd9370dcbf";
  }

  static const char* value(const ::robot_vision::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1784bb36e3cc3f55ULL;
  static const uint64_t static_value2 = 0xb84f76dd9370dcbfULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_vision::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_vision/BoundingBox";
  }

  static const char* value(const ::robot_vision::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_vision::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 xmin\n"
"int64 ymin\n"
"int64 xmax\n"
"int64 ymax\n"
"float64 confidence\n"
"string Class\n"
;
  }

  static const char* value(const ::robot_vision::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_vision::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
      stream.next(m.confidence);
      stream.next(m.Class);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_vision::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_vision::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "xmin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymax);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Class);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_VISION_MESSAGE_BOUNDINGBOX_H
